spring:
  application:
    name: ipl-dashboard
  jpa:
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true

server:
  port: 8090

management:
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    metrics:
      enabled: true
    env:
      enabled: true